# Generated by Django 6.0.6 on 2026-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='upload/gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=30, null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='upload/rooms')),
                ('guests_capacity', models.PositiveIntegerField(default=1)),
                ('beds', models.CharField(max_length=150)),
                ('price_per_night', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price_per_night', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('is_in_service', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
